prototype Regexes
{
  str  @alphabetic_character();
  str  @alphabetic_character_space_lk(str &regex_Description, str &rS);
  str  @alphanumeric_space_period(str &regex_Description, str &rS);
  str  @anything(str &regex_Description, str &rS);
  str  @batch_file_label();
  str  @big_segment();
  str  @blank_line(str &regex_Description, str &rS);
  str  @bol_colon(str &regex_Description, str &rS);
  str  @bol_colon_colon_eol_eol(str &regex_Description, str &rS);
  str  @bol_colon_eol_eol(str &regex_Description, str &rS);
  str  @bol_comma(str &regex_Description, str &rS);
  str  @bol_space(str &regex_Description, str &rS);
  str  @bol_space_eol(str &regex_Description, str &rS);
  str  @bullet_or_big_segment();
  str  @broken_cmac_macro(str &regex_Description, str &rS);
  str  @broken_lc(str &regex_Description, str &rS);
  str  @bsr();
  str  @bullet();
  str  @bullet_text();
  str  @childless_rubric();
  str  @citation_needed(str &regex_Description, str &rS);
  str  @clarification_needed(str &regex_Description, str &rS);
  str  @close_parenthesis_number(str &regex_Description, str &rS);
  str  @cmac_function_header();
  str  @colon_period_space_period();
  str  @comma_nonspace(str &regex_Description, str &rS);
  str  @comma_lc();
  str  @content_area();
  str  @crowded_noun(str &regex_Description, str &rS);
  str  @defined_for_kids(str &regex_Description, str &rS);
  str  @family_rubric();
  str  @family_rubric_text();
  str  @fat_bullet(str &regex_Description, str &rS);
  str  @fat_rubric(str &regex_Description, str &rS);
  str  @first_known_use(str &regex_Description, str &rS);
  str  @informal_followed_by_a_crowding(str &regex_Description, str &rs);
  str  @language_learner(str &regex_Description, str &rs);
  str  @learn_to_pronounce(str &regex_Description, str &rS);
  str  @lc();
  str  @lc_ending_in_2_letters(str last_Two_Letters_of_lc);
  // (!sp)
  str  @letter_space_close_parenthesis(str &regex_Description, str &rs);
  str  @lookup_counter();
  str  @mobile_colon(str &regex_Description, str &rs);
  str  @open_bracket_space(str &regex_Description, str &rS);
  str  @open_parenthesis_space_letter(str &regex_Description, str &rS);
  str  @period_colon(str &regex_Description, str &rS);
  str  @period_space_eol(str &regex_Description, str &rS);
  str  @period_space_space_alpha_char(str &regex_Description, str &rS);
  str  @question_mark_colon_space_lk(str &regex_Description, str &rS);
  str  @read_more_answers_dot_com(str &regex_Description, str &rS);
  str  @rhymes_with(str &regex_Description, str &rS);
  str  @rubric();
  str  @rubric_text();
  str  @share_american_heritage_dot_com(str &regex_Description, str &rS);
  str  @show_ipa(str &regex_Description, str &rS);
  str  @small_segment();
  str  @space_colon(str &regex_Description, str &rS);
  str  @space_close_bracket(str &regex_Description, str &rS);
  str  @space_comma(str &regex_Description, str &rS);
  str  @space_eol_blank_line(str &regex_Description, str &rS);
  str  @space_space_dash_space_space(str &regex_Description, str &rS);
  str  @space_space_eol(str &regex_Description, str &rS);
  str  @space_space(str &regex_Description, str &rS);
  str  @special_character(str &regex_Description, str &rS, str sc);
  str  @ssn();
  str  @subbullet();
  str  @subrubric();
  str  @subrubric_text();
  str  @synonyms_space_space(str &regex_Description, str &rS);
  str  @thin_bullet(str &regex_Description, str &rS);
  str  @thin_rubric(str &regex_Description, str &rS);
  str  @thinner_rubric(str &regex_Description, str &rS);
  str  @thinnest_rubric(str &regex_Description, str &rS);
  str  @uppercase_clif(str &regex_Description, str &rS);
  str  @wikipedia_annotation(str &regex_Description, str &rS);
  str  @wikipedia_annotation_2_digits(str &regex_Description, str &rS);
  str  @wikipedia_citation(str &regex_Description, str &rS);
  str  @word_history_space_space(str &regex_Description, str &rS);
}
